# Generated by Django 6.1 on 2026-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(max_length=200)),
                ('azienda', models.CharField(max_length=200)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, help_text='Lascia vuoto se è il ruolo attuale', null=True)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('linguaggio', 'Linguaggio'), ('framework', 'Framework / Tool di test'), ('ci_cd', 'CI/CD'), ('altro', 'Altro')], default='altro', max_length=20)),
                ('frequenza', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Usato nell'URL, es: playwright-gestione-catene", unique=True)),
                ('descrizione', models.TextField()),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('stelle_github', models.PositiveIntegerField(default=0)),
                ('ultimo_commit', models.DateTimeField(blank=True, null=True)),
                ('in_evidenza', models.BooleanField(default=False, help_text='Mostralo per primo in home')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('tecnologie', models.ManyToManyField(blank=True, related_name='progetti', to='core.skill')),
            ],
        ),
    ]
