# Generated by Django 6.1 on 2026-08-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='categoria',
            field=models.CharField(choices=[('linguaggio', 'Linguaggio'), ('framework', 'Framework / Tool di test'), ('ci_cd', 'CI/CD'), ('database', 'Database / Infrastruttura'), ('altro', 'Altro')], default='altro', max_length=20),
        ),
    ]
