# Generated by Django 6.1 on 2026-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Link al sito/app deployata (se esiste)', null=True),
        ),
    ]
