# Generated by Django 6.1 on 2026-08-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_demo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(choices=[('progettazione', 'Progettazione e sviluppo'), ('diagnosi', 'Diagnosi e risoluzione'), ('individuazione', 'Individuazione e documentazione'), ('costruzione', 'Costruzione e ottimizzazione'), ('audit', 'Audit e revisione'), ('redazione', 'Redazione e reportistica'), ('studio', 'Studio e implementazione')], max_length=20)),
                ('area', models.CharField(choices=[('automation', 'Test Automation'), ('ci_cd', 'CI/CD'), ('mobile', 'Mobile Testing'), ('bug_hunting', 'Bug Hunting & Security'), ('documentazione', 'Documentazione'), ('altro', 'Altro')], max_length=20)),
                ('dettaglio', models.CharField(help_text="Il 'cosa': es. 'framework di test E2E in Cypress per la piattaforma Impronto Enterprise'", max_length=300)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione (0 = primo)')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.experience')),
                ('tecnologie', models.ManyToManyField(blank=True, related_name='highlights', to='core.skill')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
    ]
