# Generated by Django 6.1 on 2026-09-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('messaggio', models.TextField()),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('letto', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='Formazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text='Es: Master Full Stack Developer', max_length=200)),
                ('istituto', models.CharField(help_text='Es: Epicode', max_length=200)),
                ('istituto_url', models.URLField(blank=True, help_text="Link al sito dell'istituto (opzionale)", null=True)),
                ('periodo_label', models.CharField(help_text="Testo libero mostrato in alto a destra. Es: '2025', '2009 — 2011', 'Corso di Formazione'", max_length=100)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione (0 = primo)')),
            ],
            options={
                'verbose_name': 'Formazione / Certificazione',
                'verbose_name_plural': 'Formazione & Certificazioni',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='FormazioneHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(help_text="Es: 'Percorso intensivo di programmazione incentrato su' — le tecnologie selezionate sotto verranno aggiunte come tag alla fine della frase.", max_length=300)),
                ('certificazione', models.CharField(blank=True, help_text="Se compilato, viene mostrato come badge esteso a sé stante (es. 'Epicode Talent - Full Stack Developer'), utile per bullet tipo 'Conseguita certificazione ufficiale'.", max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione (0 = primo)')),
                ('formazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.formazione')),
                ('tecnologie', models.ManyToManyField(blank=True, related_name='formazioni_highlights', to='core.skill')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
    ]
